// <auto-generated />
using System;
using GuitarStock.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GuitarStock.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210416114421_addGuitarsToDatabase")]
    partial class addGuitarsToDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GuitarStock.Models.Guitar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ActivePickups")
                        .HasColumnType("bit");

                    b.Property<string>("Binding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BridgePickup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BridgeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FretCount")
                        .HasColumnType("int");

                    b.Property<string>("FretSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FretboardMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InlayStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddlePickup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NeckJoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NeckPickup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickupConfiguration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickupSwitch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StringCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Guitars");
                });
#pragma warning restore 612, 618
        }
    }
}
